scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.57
    upper_angle: 1.57
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: -.inf
    upper_threshold: 2.0
    lower_replacement_value: -.inf
    upper_replacement_value: .inf
- name: intensity
  type: laser_filters/LaserScanIntensityFilter
  params:
    lower_threshold: 0
    upper_threshold: 100000
    disp_histogram: 0